In [0]:
#Create a Dataframe for this given data

data= [("James","","Smith","36636","M",60000),

        ("Michael","Rose","","40288","M",70000),

        ("Robert","","Williams","42114","",400000),

        ("Maria","Anne","Jones","39192","F",500000),

        ("Jen","Mary","Brown","","F",0)]

In [0]:
from pyspark.sql.functions import *
from datetime import datetime, date
from pyspark.sql.types import *

In [0]:
df = spark.createDataFrame(data)

In [0]:
df.display()

_1,_2,_3,_4,_5,_6
James,,Smith,36636,M,60000
Michael,Rose,,40288,M,70000
Robert,,Williams,42114,,400000
Maria,Anne,Jones,39192,F,500000
Jen,Mary,Brown,,F,0

In [0]:
#Create a Dataframe using user defined schema (str type) with same data as given on Task 1
schema='First_name string, Middle_name string, last_name string, Id string, Gender string, salary int'

In [0]:
df2=spark.createDataFrame(data,schema)

In [0]:
df2.display()

First_name,Middle_name,last_name,Id,Gender,salary
James,,Smith,36636,M,60000
Michael,Rose,,40288,M,70000
Robert,,Williams,42114,,400000
Maria,Anne,Jones,39192,F,500000
Jen,Mary,Brown,,F,0

In [0]:
#Create a Dataframe using user defined schema (List type) with same data as given on Task 1
userschema=['Firstname','Middle name','lastanme','Id','Gender','Salary']
df3=spark.createDataFrame(data,schema=userschema)
df3.display()

Firstname,Middle name,lastanme,Id,Gender,Salary
James,,Smith,36636,M,60000
Michael,Rose,,40288,M,70000
Robert,,Williams,42114,,400000
Maria,Anne,Jones,39192,F,500000
Jen,Mary,Brown,,F,0

In [0]:
#Create a Dataframe using user defined schema (pyspark data type) with same data as given on Task 1
users_schema= StructType([StructField("Firstname",StringType()),
                          StructField("Middlename",StringType()),
                          StructField("Lastname",StringType()),
                          StructField("Id",StringType()),
                          StructField("Gender",StringType()),
                          StructField("Salary",IntegerType()),
                          

])
df4=spark.createDataFrame(data,schema=users_schema)
df4.display()

Firstname,Middlename,Lastname,Id,Gender,Salary
James,,Smith,36636,M,60000
Michael,Rose,,40288,M,70000
Robert,,Williams,42114,,400000
Maria,Anne,Jones,39192,F,500000
Jen,Mary,Brown,,F,0

In [0]:
#Create a Dataframe for this given data
import datetime
users=[{"id":1, 
       "first_name":'Sachin',
       "last_name":'Tendulkar',
        "mail":'sachin@mail.com',
        "phone_numbers": ["+1 234 567 789 ", "+91 123987645"],
        "is_customer":True,
        "amount_paid":1000.2,
        "customer_from":datetime.date(2002,12,31),
        "last_update_ts":datetime.date(2022,1,1)
       }, 
       {"id":2, 
       "first_name":'M S',
       "last_name":'Dhoni',
        "mail":'mahi@mail.com',
        "phone_numbers": ["+1 789 567 234 ", "+91 124137645"],
        "is_customer":True,
        "amount_paid":2000.4,
        "customer_from":datetime.date(2004,5,30),
        "last_update_ts":datetime.date(2022,11,29)
       },
       {"id":3, 
       "first_name":'Rahul',
       "last_name":'Dravid',
        "mail":'Rahul@mail.com',
        "phone_numbers": [" ", "+91 124137645"],
        "is_customer":True,
        "amount_paid":3000.0,
        "customer_from":datetime.date(2016,3,18),
        "last_update_ts":datetime.date(2020,3,24)
       },
       {"id":4, 
       "first_name":'Hardik',
       "last_name":'pandya',
        "mail":'hardik@mail.com',
        "phone_numbers": ["+1 789 567 234 ", " "],
        "is_customer":True,
        "amount_paid":1500.5,
        "customer_from":datetime.date(1990,12,3),
        "last_update_ts":datetime.date(2022,3,2)
       },
       {"id":5, 
       "first_name":'Shubman',
       "last_name":'Gill',
        "mail":'shubman@mail.com',
        "phone_numbers": [" ", " "],
        "is_customer":True,
        "amount_paid":500.5,
        "customer_from":datetime.date(1995,2,19),
        "last_update_ts":datetime.date(2022,1,21)
       }
       
]

In [0]:
import pandas as pd

In [0]:
pandas_df=pd.DataFrame(users)
df5=spark.createDataFrame(pandas_df)
df5.show()

+---+----------+---------+----------------+--------------------+-----------+-----------+-------------+--------------+
| id|first_name|last_name|            mail|       phone_numbers|is_customer|amount_paid|customer_from|last_update_ts|
+---+----------+---------+----------------+--------------------+-----------+-----------+-------------+--------------+
|  1|    Sachin|Tendulkar| sachin@mail.com|[+1 234 567 789 ,...|       true|     1000.2|   2002-12-31|    2022-01-01|
|  2|       M S|    Dhoni|   mahi@mail.com|[+1 789 567 234 ,...|       true|     2000.4|   2004-05-30|    2022-11-29|
|  3|     Rahul|   Dravid|  Rahul@mail.com|  [ , +91 124137645]|       true|     3000.0|   2016-03-18|    2020-03-24|
|  4|    Hardik|   pandya| hardik@mail.com|[+1 789 567 234 ,  ]|       true|     1500.5|   1990-12-03|    2022-03-02|
|  5|   Shubman|     Gill|shubman@mail.com|              [ ,  ]|       true|      500.5|   1995-02-19|    2022-01-21|
+---+----------+---------+----------------+--------------------+-----------+-----------+-------------+--------------+

In [0]:
#Create a Dataframe using user defined schema (pyspark data type) with same data as given on Task 5 
users_schema1= StructType([StructField("Id",LongType()),
                          StructField("First_name",StringType()),
                          StructField("Last_name",StringType()),
                          StructField("mail",StringType()),
                          StructField("phonenumbers",ArrayType(StringType())),
                          StructField("iscustomer",BooleanType()),
                          StructField("Amountpaid",DoubleType()),
                          StructField("customerfrom",DateType()),
                          StructField("Lastupdate",DateType()),

])
df6=spark.createDataFrame(pandas_df,schema=users_schema1)
df6.show()

+---+----------+---------+----------------+--------------------+----------+----------+------------+----------+
| Id|First_name|Last_name|            mail|        phonenumbers|iscustomer|Amountpaid|customerfrom|Lastupdate|
+---+----------+---------+----------------+--------------------+----------+----------+------------+----------+
|  1|    Sachin|Tendulkar| sachin@mail.com|[+1 234 567 789 ,...|      true|    1000.2|  2002-12-31|2022-01-01|
|  2|       M S|    Dhoni|   mahi@mail.com|[+1 789 567 234 ,...|      true|    2000.4|  2004-05-30|2022-11-29|
|  3|     Rahul|   Dravid|  Rahul@mail.com|  [ , +91 124137645]|      true|    3000.0|  2016-03-18|2020-03-24|
|  4|    Hardik|   pandya| hardik@mail.com|[+1 789 567 234 ,  ]|      true|    1500.5|  1990-12-03|2022-03-02|
|  5|   Shubman|     Gill|shubman@mail.com|              [ ,  ]|      true|     500.5|  1995-02-19|2022-01-21|
+---+----------+---------+----------------+--------------------+----------+----------+------------+----------+

In [0]:
#Use Df from task 6 and create new dataframe where first_name and last_name should be one column.
df7=df6.select(concat("First_name",lit(" "),"Last_name").alias("full_name")).show()

+----------------+
|       full_name|
+----------------+
|Sachin Tendulkar|
|       M S Dhoni|
|    Rahul Dravid|
|   Hardik pandya|
|    Shubman Gill|
+----------------+

In [0]:
#Use df from task 6 and Get this Output:


df6.select("First_name","Last_name", lit('Cricketers').alias("Sports")).show()

+----------+---------+----------+
|First_name|Last_name|    Sports|
+----------+---------+----------+
|    Sachin|Tendulkar|Cricketers|
|       M S|    Dhoni|Cricketers|
|     Rahul|   Dravid|Cricketers|
|    Hardik|   pandya|Cricketers|
|   Shubman|     Gill|Cricketers|
+----------+---------+----------+